sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - "7"
  - "8"
fast_finish: true
before_install:
  - npm i npm@^5 -g
install:
  - npm install
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
script:
  - node -v && npm -v
  - npm run e2e
  - npm run test:ci
cache:
  directories:
    - node_modules
